# Generated by Django 3.1.7 on 2021-03-15 18:37

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('edited', models.DateField(auto_now=True, verbose_name='Editado')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('type', models.CharField(choices=[('simple', 'Simples'), ('medication', 'Medicação'), ('observation', 'Observação'), ('band_aid', 'Curativo'), ('suture', 'sutura'), ('withdrawal', 'Retirada de Pontos'), ('rh', 'RH')], max_length=18, verbose_name='Tipo da consulta')),
                ('name', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('sus', models.IntegerField(verbose_name='Número do SUS')),
                ('sex', models.CharField(choices=[('male', 'M'), ('female', 'F'), ('another', 'o')], max_length=7, verbose_name='Sexo')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('consultation_date', models.DateField(verbose_name='Data da consulta')),
                ('medical_record', stdimage.models.StdImageField(upload_to='medical_records', verbose_name='Ficha médica')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
