# Generated by Django 3.1.7 on 2021-03-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='sex',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino'), ('another', 'Outro')], max_length=9, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='sus',
            field=models.CharField(max_length=15, verbose_name='Número do SUS'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='type',
            field=models.CharField(choices=[('simple', 'Simples'), ('medication', 'Medicação'), ('observation', 'Observação'), ('band_aid', 'Curativo'), ('suture', 'Sutura'), ('withdrawal', 'Retirada de Pontos'), ('rh', 'RH')], max_length=18, verbose_name='Tipo da consulta'),
        ),
    ]
