# Generated by Django 3.1.7 on 2021-03-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210315_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'verbose_name': 'Ficha médica', 'verbose_name_plural': 'Fichas médicas'},
        ),
    ]
